name: Publish puix to NPM
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Publish NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm run lint
      - run: npm t
      - run: npm i
      - run: npm run build
        env:
          CI: true